services:
  app:
    build:
      context: ..
      dockerfile: docker/dockerfile
    container_name: gorm-app
    env_file:
      - ../.env
    environment:
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_DB: mydb
      MONGO_USER: ""
      MONGO_PASS: ""
      POSTGRES_HOST: postgres
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      - mongo
      - postgres
      - redis
    ports:
      - "8080:8080"
    networks:
      - backend

  mongo:
    image: mongo:7
    container_name: mongo
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASS}
      MONGO_INITDB_DATABASE: ${MONGO_DB}
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - backend

  postgres:
    image: postgres:16-alpine
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
      POSTGRES_USER: gorm
      POSTGRES_DB: gorm
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - backend

  redis:
    image: redis:7-alpine
    container_name: redis
    restart: unless-stopped
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - backend
  
  frontend:
    image: node:20-alpine
    container_name: frontend
    working_dir: /app
    volumes:
      - ../frontend:/app
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0 --port 5173 --strictPort"
    environment:
      - CHOKIDAR_USEPOLLING=true
    ports:
      - "5173:5173"
    depends_on:
      - app
    networks:
      - backend

volumes:
  mongo_data:
  postgres_data:
  redis_data:

networks:
  backend:
    driver: bridge
