-- Migration: post_003_drop_legacy_fk_constraints
-- Phase: POST-AutoMigrate
-- Description: Remove FK constraints auto-generated by GORM on contact_data_bases.
--              These are replaced by application-level (logical) references so that
--              soft-deleted users do not break contact lookups.

DO $$ BEGIN
    IF EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE constraint_name = 'fk_contact_data_bases_user'
    ) THEN
        ALTER TABLE contact_data_bases DROP CONSTRAINT fk_contact_data_bases_user;
    END IF;

    IF EXISTS (
        SELECT 1 FROM information_schema.table_constraints
        WHERE constraint_name = 'fk_contact_data_bases_user_contact'
    ) THEN
        ALTER TABLE contact_data_bases DROP CONSTRAINT fk_contact_data_bases_user_contact;
    END IF;
END $$;
